### ISSUE TITLE
Python 3.9 with Windows 10 error

### ISSUE THREAD

**Issue by jasepower** [sachapan/scripts#1]
script output error (edited with <userprofile> in place of full path):

Traceback (most recent call last):
  File "<userprofile>\srt_cleanup.py", line 17, in <module>
    soup = BeautifulSoup(file1,"html.parser")
  File "C:\Users\<userprofile>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\bs4\__init__.py", line 311, in __init__
    markup = markup.read()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 35: invalid continuation byte

**Comment by sachapan** [comment]
Thanks for the interest.
The specific error looks like it is related to the input file:  'utf-8' codec can't decode byte 0xea in position 35: invalid continuation byte. '  
I have uploaded a sample subtitle file:  https://raw.githubusercontent.com/sachapan/scripts/main/sample.srt  
Are you able to test with this file and report the results?  This should help determine if the issue is in the input or the program.

**Comment by jasepower** [comment]
Output from sample:
Subtitle processing complete.
Output is now available in file: output.txt

It succeeded :)

**Comment by sachapan** [comment]
Thanks for confirming!  This means the trouble is with the input file being used.  The script is hard-coded to import (and export) utf-8 encoded files which may be the trouble.  I have typically used ffmpeg (https://ffmpeg.org/) to perform the initial extraction from the video file if that helps with your workflow.  If you'd like to post a sample of the file that is misbehaving, I'd be happy to take a further look.

**Comment by jasepower** [comment]
The mystery continues. If you check the file I sent you it is encoded as utf-8. If it helps, I extracted the srt using My MP4Box and not ffmpeg.
